version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.0.1

jobs:
  checkout_and_install_npm:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  eslint:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./
      - run: npm run lint:eslint

  webext-lint:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./
      - run: npm run lint:webext

  unit-test:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./
      - run: npm run test:unit

  unit-test-coverage:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./
      - run: npm run ci:coverage

  end-to-end-test:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./
      - browser-tools/install-firefox
      - run: npm run test:end-to-end

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_and_install_npm
      - eslint:
          requires:
            - checkout_and_install_npm
      - webext-lint:
          requires:
            - checkout_and_install_npm
      - unit-test:
          requires:
            - checkout_and_install_npm
      - unit-test-coverage:
          requires:
            - checkout_and_install_npm
      - end-to-end-test:
          requires:
            - checkout_and_install_npm
