version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.0.1

jobs:
  checkout_and_install_npm:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  eslint:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./
      - run: npm run lint:eslint

  webext-lint:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./
      - run: npm run lint:webext

  unit-test:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./
      - run: npm run ci:unit-test

  contract-test:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./
      - run: npm run test:html-contracts

  end-to-end-test:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./
      - browser-tools/install-firefox
      - run: npm run test:end-to-end

  tool-test:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./
      - run: npm run test:tools

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./
      - run: npm run build

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - checkout_and_install_npm:
          filters:
            tags:
              only: /.*/
      - eslint:
          requires:
            - checkout_and_install_npm
          filters:
            tags:
              only: /.*/
      - webext-lint:
          requires:
            - checkout_and_install_npm
          filters:
            tags:
              only: /.*/
      - unit-test:
          requires:
            - checkout_and_install_npm
          filters:
            tags:
              only: /.*/
      - contract-test:
          requires:
            - checkout_and_install_npm
          filters:
            tags:
              only: /.*/
      - end-to-end-test:
          requires:
            - checkout_and_install_npm
          filters:
            tags:
              only: /.*/
      - tool-test:
          requires:
            - checkout_and_install_npm
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - eslint
            - webext-lint
            - unit-test
            - contract-test
            - end-to-end-test
            - tool-test
          filters:
            tags:
              only: /^v.+/
            branches:
              ignore: /.*/
  daily:
    triggers:
      - schedule:
          cron: '16 16 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - checkout_and_install_npm
      - contract-test:
          requires:
            - checkout_and_install_npm
      - end-to-end-test:
          requires:
            - checkout_and_install_npm
